### ISSUE TITLE
感谢贴

### ISSUE THREAD

**Issue by 94club** [geek-prince/react-native-page-scrollview#2]
感谢作者开源，ORZ
安装了您的插件后  按住第一张图片滑动到第二张，松手又弹回去了，imageArr的数据是在componentDidMount里面发送网络请求异步获取的，render里面是
////   {this.state.bannerList && <PageScrollView   style={{width:width,height:140}}  
////    imageArr ={this.state.bannerList}  />}
请问是什么原因呢   期待您的回答

**Comment by geek-prince** [comment]
谢谢你提出的issues.根据你的描述,我猜想会不会是你手指滚动时速度比较小的原因,你可以尝试一下将goToNextPageSpeed属性设置为比较小一点的数字(默认为3,可以给浮点数).
<PageScrollView 
    goToNextPageSpeed=2.3
    //其他的一些属性
 />
这样设置试试看.
goToNextPageSpeed可以指定手指滑动时可以滑动到下一页的速度大小.速度大于多少时为有向左(右,上,下)翻一页的意图(数值越大,要滑动速度越快(越难)才能到下一页,数值越小,滑动越慢(越容易)可以到下一页)
