### ISSUE TITLE
高级轮播-自定义View

### ISSUE THREAD

**Issue by iwesion** [geek-prince/react-native-page-scrollview#3]
当我滑动自定义的View的时候{size,opacity,rotate,skew}返回全部都变成NaN了 
代码 <PageScrollView
            style={{width:w,height:100,margin:10}}
            sizeSmall={0.5}
            opacitySmall={0.6}
            rotateDeg={30}
            skewDeg={45}
            datas={[1,2,3]}
            currentPageChangeFunc={(e)=>console.log(e)}
            view={(i,data,{size,opacity,rotate,skew})=>{
              console.log(i,data,{size,opacity,rotate,skew})
              this.r = Math.floor(Math.random()*255);
              this.g = Math.floor(Math.random()*255);
              this.b = Math.floor(Math.random()*255);
          let color = 'rgba('+ this.r +','+ this.g +','+ this.b +',0.8)';
              return(

                    <View style={{width:w*size,height:60*size,justifyContent:'center',alignItems:'center',backgroundColor:color}}>
                      <Text>{i}</Text>
                    </View>

                );
            }}
          />

**Comment by geek-prince** [comment]
我把你的代码复制粘贴过来后,是可以打印出数值的呀.
你再检查一下,是不是代码的其他地方出错了

**Comment by iwesion** [comment]
新开界面测试还是滑动一下就不能滑动了，返回值全是NaN

**Comment by geek-prince** [comment]
你具体说说是什么情况下返回的NaN,不能滑动是手指滑动时组件没有反应吗?

**Comment by iwesion** [comment]
方便留个联系方式么，我把打印截图给你看下

**Comment by geek-prince** [comment]
1559199369你加这个qq吧
