### ISSUE TITLE
起始页怎么设置?

### ISSUE THREAD

**Issue by Coder108** [geek-prince/react-native-page-scrollview#5]
我想设置一打开就显示第二个page 但我不知道哪个属性可以设置,请问有解决方法吗?

**Comment by geek-prince** [comment]
可以的,在"拓展与进阶"中有写到
有的时候我们不想组件一开始显示的是第一张图片或View,这时可以通过didMount属性(组件加载好后,并且布局好得到相应宽高后的执行的操作)来让组件加载好后滚动到相应索引的图片或自定义View.didMount={()=>{this.pageScrollView.manualScrollToPage(4);}}
这个版本可以先这样解决,但是效果不是很好,这个组件也还有一些不太完善的地方我准备最近可能会更新一版
