### ISSUE TITLE
install后，import后，进入抛错了。

### ISSUE THREAD

**Issue by zuijiusi** [geek-prince/react-native-page-scrollview#6]
<PageScrollView 
          style={{width:300,height:160}}
          imageArr={this.state.imgList}
        />
nvariant Violation: Invariant Violation: [145,"RCTView",91,{"width":"<<NaN>>","height":0,"backgroundColor":0}] is not usable as a native method argument

**Comment by geek-prince** [comment]
你这边用的rn的版本是多少呢?

**Comment by zuijiusi** [comment]
> 
> 
> 你这边用的rn的版本是多少呢?

"react-native": "^0.58.6"

**Comment by geek-prince** [comment]
你是怎么使用这个组件的呢?这个具体要看一下你使用的方法,你把你的代码粘贴一下,我看看吧

**Comment by quweifan** [comment]
rn版本是：0.59.1  抛出异常：nvariant Violation: Invariant Violation: [145,"RCTView",91,{"width":"<>","height":0,"backgroundColor":0}] is not usable as a native method argument

**Comment by geek-prince** [comment]
你把你这个组件部分的代码粘贴一下,我看看吧
