### ISSUE TITLE
你这个项目rn是用的哪个版本啊

### ISSUE THREAD

**Issue by fengluhui** [geek-prince/react-native-page-scrollview#8]

**Comment by geek-prince** [comment]
这个组件大概是我半年前写的了,你这边是在现在rn的新版本上使用时有什么问题吗?

**Comment by fengluhui** [comment]
didMount={()=>{this.pageScrollView.manualScrollToPage(4);}}调用这个属性时，刚进入页面会出现闪动，会先显示第一个view再显示我设置的第四个view

**Comment by fengluhui** [comment]
进入页面时不会自动到需要的view,而是有一个滚动效果
