### ISSUE TITLE
Invariant Violation: [19,"RCTView",21,{"width":"<<NaN>>","height":0,"backgroundColor":0}] is not usable as a native method argument

### ISSUE THREAD

**Issue by ghost** [geek-prince/react-native-page-scrollview#9]
![image](https://user-images.githubusercontent.com/32088612/57275428-21db3280-70d1-11e9-8a9f-0534339909a9.png)

![image](https://user-images.githubusercontent.com/32088612/57275459-35869900-70d1-11e9-9779-f14b13234eae.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/32088612/57275636-b34aa480-70d1-11e9-8a8f-3fd1d9596e82.png)

**Comment by geek-prince** [comment]
你用的react-native版本是较新的版本吗?大家最近反馈这个问题大多数都是在较新版本的出现的,但是最近还没时间来得及更新,你可以用下面这个用户找到的临时方法来解决一下:

![图片](https://user-images.githubusercontent.com/18375471/57289427-ed29a400-70ed-11e9-807e-5754d91fe277.png)

在源码中加入宽高的默认值

**Comment by ghost** [comment]
版本是最新的

**Comment by geek-prince** [comment]
那你先用这个方法临时解决一下吧,我后面有时间时会更新一个版本

**Comment by ghost** [comment]
好的

**Comment by CrayonShin-chan** [comment]
这么久了 这个问题还不更新掉吗？

**Comment by miyaliunian** [comment]
大佬 可以帮你 pr吗

**Comment by geek-prince** [comment]
@miyaliunian 行吧,你们有什么其他好的想法也都可以pr过来看看,现在还没什么时间来维护这些库

**Comment by r-j-q** [comment]
> 那你先用这个方法临时解决一下吧,我后面有时间时会更新一个版本

项目升级后react-native-gesture-handler报invariant找不到，这怎么解决啊
